language: node_js
node_js:
- '16.0'
script:
- npm install
- npm run build
- npm run coverage
after_success:
- curl -s https://codecov.io/bash > .codecov
- chmod +x .codecov
- ./.codecov -t b9934e23-c6f2-4a95-8c21-5ed5c20d5976